/**
 * Client bundle build (docs/product-design.md 14.1, 14.4).
 *
 * Produces lib/client.js in the DSH ModuleLoader closure format: the bundle
 * calls window.__ModuleLoader__.load({ id, factory }) with the factory
 * receiving the injected require. The baseline platform modules (react,
 * react-dom, cordis, the client UI kits) stay external and resolve through
 * the browser module table at runtime. Inline styles only - no stylesheet
 * pipeline. Run via `pnpm run build:client` after `pnpm run build`.
 */

import { build } from 'esbuild'

const externals = [
  'react',
  'react/*',
  'react-dom',
  'react-dom/*',
  '@deepseek-ai/cordis',
  '@deepseek-ai/dsh-client-store',
  '@deepseek-ai/dsh-client-ui-slots',
  '@deepseek-ai/dsh-client-ui-primitives',
  '@deepseek-ai/dsh-client-ui-dockkit',
]

const result = await build({
  entryPoints: ['src/client/index.ts'],
  bundle: true,
  format: 'cjs',
  platform: 'browser',
  jsx: 'automatic',
  outfile: 'lib/client.js',
  external: externals,
  minify: true,
  legalComments: 'none',
  logLevel: 'info',
  write: false,
})

const banner = '/* dsh-repo-board client bundle - generated by scripts/build-client.mjs */\n'
const loaderPrelude =
  "window.__ModuleLoader__.load({ id: 'dsh-repo-board/client', factory: function (require, module, exports) {\n"
const loaderEpilogue = '\n} });\n'

const code = banner + loaderPrelude + result.outputFiles[0].text + loaderEpilogue

import { mkdir, writeFile } from 'node:fs/promises'
await mkdir('lib', { recursive: true })
await writeFile('lib/client.js', code, 'utf8')
console.log('lib/client.js written:', code.length, 'bytes')
